# Generated by Django 4.2.7 on 2023-11-16 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collecte',
            fields=[
                ('identifiant_collecte', models.AutoField(primary_key=True, serialize=False)),
                ('detail_panier', models.JSONField()),
            ],
            options={
                'db_table': 'collecte',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('identifiant_client', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_enfants', models.IntegerField()),
                ('categorie_socioprofessionnelle', models.CharField(max_length=50)),
                ('prix_panier', models.DecimalField(decimal_places=2, max_digits=10)),
                ('identifiant_collecte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Analyses.collecte')),
            ],
            options={
                'db_table': 'client',
            },
        ),
    ]
